name: build ad-llama

on:
  push:
    branches:
      - gh-action

jobs:
  build-tvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get submodule commit hash
        id: submodule-status
        run: echo "status=$(git submodule status | sed 's/\ /_/')" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            3rdparty/relax/web/lib
            3rdparty/relax/web/dist
          key: ${{ steps.submodule-status.outputs.status }}

      - name: pull submodules
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: git submodule update --init

      - name: setup emsdk
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43
          actions-cache-folder: '__emsdk-cache'

      - name: build tvm dependency
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          cd 3rdparty/relax/web
          make

  build-ad-llama:
    runs-on: ubuntu-latest
    needs: build-tvm
    steps:
      - uses: actions/checkout@v3
      - name: build ad-llama
        run: npm i && npm run build
