name: publish typedocs to github pages

on:
  workflow_run:
    workflows: [build ad-llama]
    types:
      - completed

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - id: cache
        uses: ./.github/actions/cache-tvm
      - run: |
          npm ci
          npm run docs -- --gitRevision ${{ github.ref_name }}
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs
      - name: deploy to github pages
        uses: actions/deploy-pages@v2
        id: deployment
